import { createContext, useContext, useState } from "react";

export const scheduledLanguages = [
  ["en", "English"],
  ["as", "অসমীয়া"],
  ["bn", "বাংলা"],
  ["bo", "बोडो"],
  ["doi", "डोगरी"],
  ["gu", "ગુજરાતી"],
  ["hi", "हिन्दी"],
  ["kn", "ಕನ್ನಡ"],
  ["ks", "कश्मीरी"],
  ["kok", "कोंकणी"],
  ["mai", "मैथिली"],
  ["ml", "മലയാളം"],
  ["mni", "মৈতৈলোন্"],
  ["mr", "मराठी"],
  ["ne", "नेपाली"],
  ["or", "ଓଡ଼ିଆ"],
  ["pa", "ਪੰਜਾਬੀ"],
  ["sa", "संस्कृतम्"],
  ["sat", "ᱥᱟᱱᱛᱟᱲᱤ"],
  ["sd", "سنڌي"],
  ["ta", "தமிழ்"],
  ["te", "తెలుగు"],
  ["ur", "اردو"]
];

const translations = {
  en: {
    government: "Government of India • Agriculture & Farmer Welfare",
    skip: "Skip to main content",
    language: "Language",
    home: "Home",
    howItWorks: "How it works",
    publicReports: "Public Reports",
    farmerLogin: "Farmer Login",
    officerLogin: "Officer Login",
    heroEyebrow: "Agriculture & Farmer Welfare",
    heroTitle: "One place to discover government schemes meant for you.",
    heroText: "Kisan Connect combines your farming profile, location and household indicators to surface relevant agricultural schemes and explain why they may match.",
    register: "Register as a Farmer",
    disclaimer: "Eligibility scores are decision-support indicators, not legal eligibility determinations.",
    services: "Farmer services",
    publicAnalytics: "Public analytics",
    reportsTitle: "Farmers using the platform",
    reportsDescription: "Explore anonymized state-level activity and the geographic conditions represented in the public demo dataset.",
    registered: "registered farmers in demo dataset",
    stateActivity: "State activity",
    hoverHint: "Hover over a state to view farmer count, share and geographic condition.",
    farmerCount: "farmers",
    share: "platform share",
    condition: "geographic condition",
    legend: "Farmer concentration",
    low: "Lower",
    high: "Higher",
    farmerServices: "Farmer services",
    farmerLoginTitle: "Farmer Login",
    loginDescription: "Access your profile, matched schemes, saved schemes and application status.",
    signInTitle: "Sign in to Kisan Connect",
    mobileNumber: "Mobile Number",
    password: "Password",
    login: "Login",
    signingIn: "Signing in...",
    registerPrompt: "New farmer?",
    registerHere: "Register here",
    farmerDashboard: "Farmer dashboard",
    welcome: "Welcome",
    updateProfile: "Update Profile",
    matchedSchemes: "Matched schemes",
    savedSchemes: "Saved schemes",
    applications: "Applications",
    eviScore: "EVI score",
    recommended: "Recommended",
    matchedToProfile: "Schemes matched to your profile",
    viewAll: "View all",
    noRecommendations: "No recommendations are available yet.",
    recentActivity: "Recent activity",
    noApplications: "No applications yet.",
    viewApplications: "View applications",
    yourEvi: "Your EVI",
    calculatedProfile: "Calculated from your current profile",
    registration: "Farmer Registration",
    newRegistration: "New Farmer Registration",
    completeProfile: "Complete your profile so the backend can calculate your EVI and match relevant government schemes.",
    previous: "Previous",
    continue: "Continue",
    creatingAccount: "Creating account...",
    submitRegistration: "Submit Registration",
    registrationSuccessful: "Registration successful",
    profileCreated: "Farmer profile created",
    profileSaved: "Your account and extended farmer profile have been saved.",
    openDashboard: "Open Farmer Dashboard",
    backHome: "Back to Home",
    step: "Step",
    of: "of"
    ,invalidMobile: "Enter a valid 10-digit mobile number.",
    shortPassword: "Password must contain at least 8 characters.",
    notFarmerAccount: "This account is not a farmer account.",
    loadingDashboard: "Loading your farmer dashboard...",
    farmer: "Farmer"
  },
  hi: {
    government: "भारत सरकार • कृषि एवं किसान कल्याण",
    skip: "मुख्य सामग्री पर जाएं",
    language: "भाषा",
    home: "होम",
    howItWorks: "यह कैसे काम करता है",
    publicReports: "सार्वजनिक रिपोर्ट",
    farmerLogin: "किसान लॉगिन",
    officerLogin: "अधिकारी लॉगिन",
    heroEyebrow: "कृषि एवं किसान कल्याण",
    heroTitle: "अपने लिए बनाई गई सरकारी योजनाएं एक ही जगह खोजें।",
    heroText: "किसान कनेक्ट आपकी कृषि प्रोफ़ाइल, स्थान और घरेलू संकेतकों से उपयुक्त योजनाएं दिखाता है और बताता है कि वे क्यों मिलती हैं।",
    register: "किसान के रूप में पंजीकरण",
    disclaimer: "पात्रता स्कोर निर्णय-सहायक संकेतक हैं, कानूनी पात्रता का निर्धारण नहीं।",
    services: "किसान सेवाएं",
    publicAnalytics: "सार्वजनिक विश्लेषण",
    reportsTitle: "प्लेटफॉर्म का उपयोग करने वाले किसान",
    reportsDescription: "सार्वजनिक डेमो डेटा में राज्य-स्तरीय गतिविधि और भौगोलिक परिस्थितियां देखें।",
    registered: "डेमो डेटा में पंजीकृत किसान",
    stateActivity: "राज्य गतिविधि",
    hoverHint: "किसानों की संख्या, हिस्सेदारी और भौगोलिक स्थिति देखने के लिए राज्य पर जाएं।",
    farmerCount: "किसान",
    share: "प्लेटफॉर्म हिस्सेदारी",
    condition: "भौगोलिक स्थिति",
    legend: "किसान एकाग्रता",
    low: "कम",
    high: "अधिक",
    farmerServices: "किसान सेवाएं",
    farmerLoginTitle: "किसान लॉगिन",
    loginDescription: "अपनी प्रोफ़ाइल, मिलान की गई योजनाओं, सुरक्षित योजनाओं और आवेदन की स्थिति देखें।",
    signInTitle: "किसान कनेक्ट में साइन इन करें",
    mobileNumber: "मोबाइल नंबर",
    password: "पासवर्ड",
    login: "लॉगिन",
    signingIn: "साइन इन हो रहा है...",
    registerPrompt: "नए किसान?",
    registerHere: "यहां पंजीकरण करें",
    farmerDashboard: "किसान डैशबोर्ड",
    welcome: "स्वागत है",
    updateProfile: "प्रोफ़ाइल अपडेट करें",
    matchedSchemes: "मिलान की गई योजनाएं",
    savedSchemes: "सहेजी गई योजनाएं",
    applications: "आवेदन",
    eviScore: "EVI स्कोर",
    recommended: "अनुशंसित",
    matchedToProfile: "आपकी प्रोफ़ाइल से मिलान की गई योजनाएं",
    viewAll: "सभी देखें",
    noRecommendations: "अभी कोई अनुशंसा उपलब्ध नहीं है।",
    recentActivity: "हाल की गतिविधि",
    noApplications: "अभी कोई आवेदन नहीं है।",
    viewApplications: "आवेदन देखें",
    yourEvi: "आपका EVI",
    calculatedProfile: "आपकी वर्तमान प्रोफ़ाइल से गणना की गई",
    registration: "किसान पंजीकरण",
    newRegistration: "नया किसान पंजीकरण",
    completeProfile: "अपनी प्रोफ़ाइल पूरी करें ताकि बैकएंड आपका EVI निकालकर उपयुक्त सरकारी योजनाएं दिखा सके।",
    previous: "पिछला",
    continue: "जारी रखें",
    creatingAccount: "खाता बनाया जा रहा है...",
    submitRegistration: "पंजीकरण भेजें",
    registrationSuccessful: "पंजीकरण सफल",
    profileCreated: "किसान प्रोफ़ाइल बनाई गई",
    profileSaved: "आपका खाता और विस्तृत किसान प्रोफ़ाइल सहेज दी गई है।",
    openDashboard: "किसान डैशबोर्ड खोलें",
    backHome: "होम पर वापस जाएं",
    step: "चरण",
    of: "में से"
    ,invalidMobile: "मान्य 10 अंकों का मोबाइल नंबर दर्ज करें।",
    shortPassword: "पासवर्ड में कम से कम 8 अक्षर होने चाहिए।",
    notFarmerAccount: "यह किसान खाता नहीं है।",
    loadingDashboard: "आपका किसान डैशबोर्ड लोड हो रहा है...",
    farmer: "किसान"
  },
  bn: { language: "ভাষা", home: "হোম", publicReports: "সর্বজনীন প্রতিবেদন", reportsTitle: "প্ল্যাটফর্ম ব্যবহারকারী কৃষক", farmerCount: "কৃষক", condition: "ভৌগোলিক অবস্থা", stateActivity: "রাজ্যের কার্যকলাপ", legend: "কৃষকের ঘনত্ব", low: "কম", high: "বেশি" },
  gu: { language: "ભાષા", home: "હોમ", publicReports: "જાહેર અહેવાલો", reportsTitle: "પ્લેટફોર્મનો ઉપયોગ કરતા ખેડૂતો", farmerCount: "ખેડૂતો", condition: "ભૌગોલિક સ્થિતિ", stateActivity: "રાજ્ય પ્રવૃત્તિ", legend: "ખેડૂત ઘનતા", low: "ઓછી", high: "વધુ" },
  mr: { language: "भाषा", home: "मुख्यपृष्ठ", publicReports: "सार्वजनिक अहवाल", reportsTitle: "प्लॅटफॉर्म वापरणारे शेतकरी", farmerCount: "शेतकरी", condition: "भौगोलिक स्थिती", stateActivity: "राज्य गतिविधी", legend: "शेतकरी एकाग्रता", low: "कमी", high: "जास्त" },
  ta: { language: "மொழி", home: "முகப்பு", publicReports: "பொது அறிக்கைகள்", reportsTitle: "தளத்தைப் பயன்படுத்தும் விவசாயிகள்", farmerCount: "விவசாயிகள்", condition: "புவியியல் நிலை", stateActivity: "மாநில செயல்பாடு", legend: "விவசாயிகள் செறிவு", low: "குறைவு", high: "அதிகம்" },
  te: { language: "భాష", home: "హోమ్", publicReports: "ప్రజా నివేదికలు", reportsTitle: "ప్లాట్‌ఫారమ్‌ను ఉపయోగిస్తున్న రైతులు", farmerCount: "రైతులు", condition: "భౌగోళిక పరిస్థితి", stateActivity: "రాష్ట్ర కార్యకలాపం", legend: "రైతుల సాంద్రత", low: "తక్కువ", high: "ఎక్కువ" },
  kn: { language: "ಭಾಷೆ", home: "ಮುಖಪುಟ", publicReports: "ಸಾರ್ವಜನಿಕ ವರದಿಗಳು", reportsTitle: "ವೇದಿಕೆ ಬಳಸುತ್ತಿರುವ ರೈತರು", farmerCount: "ರೈತರು", condition: "ಭೌಗೋಳಿಕ ಸ್ಥಿತಿ", stateActivity: "ರಾಜ್ಯ ಚಟುವಟಿಕೆ", legend: "ರೈತರ ಸಾಂದ್ರತೆ", low: "ಕಡಿಮೆ", high: "ಹೆಚ್ಚು" },
  ml: { language: "ഭാഷ", home: "ഹോം", publicReports: "പൊതു റിപ്പോർട്ടുകൾ", reportsTitle: "പ്ലാറ്റ്ഫോം ഉപയോഗിക്കുന്ന കർഷകർ", farmerCount: "കർഷകർ", condition: "ഭൂമിശാസ്ത്രപരമായ അവസ്ഥ", stateActivity: "സംസ്ഥാന പ്രവർത്തനം", legend: "കർഷക സാന്ദ്രത", low: "കുറവ്", high: "കൂടുതൽ" },
  pa: { language: "ਭਾਸ਼ਾ", home: "ਮੁੱਖ ਪੰਨਾ", publicReports: "ਜਨਤਕ ਰਿਪੋਰਟਾਂ", reportsTitle: "ਪਲੇਟਫਾਰਮ ਦੀ ਵਰਤੋਂ ਕਰਨ ਵਾਲੇ ਕਿਸਾਨ", farmerCount: "ਕਿਸਾਨ", condition: "ਭੂਗੋਲਿਕ ਸਥਿਤੀ", stateActivity: "ਰਾਜ ਗਤੀਵਿਧੀ", legend: "ਕਿਸਾਨ ਘਣਤਾ", low: "ਘੱਟ", high: "ਵੱਧ" },
  or: { language: "ଭାଷା", home: "ମୂଳପୃଷ୍ଠା", publicReports: "ସାର୍ବଜନୀନ ରିପୋର୍ଟ", reportsTitle: "ପ୍ଲାଟଫର୍ମ ବ୍ୟବହାର କରୁଥିବା ଚାଷୀ", farmerCount: "ଚାଷୀ", condition: "ଭୌଗୋଳିକ ସ୍ଥିତି", stateActivity: "ରାଜ୍ୟ କାର୍ଯ୍ୟକଳାପ", legend: "ଚାଷୀ ଘନତା", low: "କମ", high: "ଅଧିକ" }
};

const farmerCoreTranslations = {
  as: { farmerLoginTitle: "কৃষক লগইন", signInTitle: "কিষাণ কানেক্টত ছাইন ইন কৰক", mobileNumber: "মোবাইল নম্বৰ", password: "পাছৱৰ্ড", login: "লগইন", farmerDashboard: "কৃষক ডেশ্বব’ৰ্ড", welcome: "স্বাগতম", updateProfile: "প্ৰফাইল আপডেট কৰক", matchedSchemes: "মিল থকা আঁচনি", savedSchemes: "সংৰক্ষিত আঁচনি", applications: "আবেদন", recommended: "পৰামৰ্শিত", matchedToProfile: "আপোনাৰ প্ৰফাইলৰ সৈতে মিল থকা আঁচনি", viewAll: "সকলো চাওক", recentActivity: "শেহতীয়া কাৰ্যকলাপ", yourEvi: "আপোনাৰ EVI", registration: "কৃষক পঞ্জীয়ন", newRegistration: "নতুন কৃষক পঞ্জীয়ন", previous: "পূৰ্বৱৰ্তী", continue: "আগবাঢ়ক", submitRegistration: "পঞ্জীয়ন জমা দিয়ক" },
  bn: { farmerLoginTitle: "কৃষক লগইন", signInTitle: "কিষাণ কানেক্টে সাইন ইন করুন", mobileNumber: "মোবাইল নম্বর", password: "পাসওয়ার্ড", login: "লগইন", farmerDashboard: "কৃষক ড্যাশবোর্ড", welcome: "স্বাগতম", updateProfile: "প্রোফাইল আপডেট করুন", matchedSchemes: "মিল থাকা প্রকল্প", savedSchemes: "সংরক্ষিত প্রকল্প", applications: "আবেদন", recommended: "প্রস্তাবিত", matchedToProfile: "আপনার প্রোফাইলের সঙ্গে মেলা প্রকল্প", viewAll: "সব দেখুন", recentActivity: "সাম্প্রতিক কার্যকলাপ", yourEvi: "আপনার EVI", registration: "কৃষক নিবন্ধন", newRegistration: "নতুন কৃষক নিবন্ধন", previous: "পূর্ববর্তী", continue: "চালিয়ে যান", submitRegistration: "নিবন্ধন জমা দিন" },
  bo: { farmerLoginTitle: "फार्मर लगइन", signInTitle: "किसान कनेक्टआव साइन इन", mobileNumber: "मोबाइल नम्बर", password: "पासवर्ड", login: "लगइन", farmerDashboard: "फार्मर डैसबोर्ड", welcome: "स्वागतम", updateProfile: "प्रोफाइल अपडेट", matchedSchemes: "मिलान योजना", savedSchemes: "सहेजी योजना", applications: "आवेदन", recommended: "सिफारिस", matchedToProfile: "नङो प्रोफाइलजों मिलान योजना", viewAll: "फुंनानाय", recentActivity: "दानि खामानि", yourEvi: "नोंनि EVI", registration: "फार्मर रजिस्ट्रेसन", newRegistration: "गोदान फार्मर रजिस्ट्रेसन", previous: "आगोल", continue: "सोलों", submitRegistration: "रजिस्ट्रेसन दं" },
  doi: { farmerLoginTitle: "किसान लॉगिन", signInTitle: "किसान कनेक्ट च साइन इन करो", mobileNumber: "मोबाइल नंबर", password: "पासवर्ड", login: "लॉगिन", farmerDashboard: "किसान डैशबोर्ड", welcome: "स्वागत", updateProfile: "प्रोफाइल अपडेट करो", matchedSchemes: "मिलदियां योजनां", savedSchemes: "बचाइयां योजनां", applications: "अर्जियां", recommended: "सिफारिश", matchedToProfile: "तुंदी प्रोफाइल कन्नै मेल खांदियां योजनां", viewAll: "सब दिखाओ", recentActivity: "हाल दी गतिविधि", yourEvi: "तुंदा EVI", registration: "किसान पंजीकरण", newRegistration: "नमां किसान पंजीकरण", previous: "पिछला", continue: "जारी रक्खो", submitRegistration: "पंजीकरण जमा करो" },
  gu: { farmerLoginTitle: "ખેડૂત લૉગિન", signInTitle: "કિસાન કનેક્ટમાં સાઇન ઇન કરો", mobileNumber: "મોબાઇલ નંબર", password: "પાસવર્ડ", login: "લૉગિન", farmerDashboard: "ખેડૂત ડેશબોર્ડ", welcome: "સ્વાગત છે", updateProfile: "પ્રોફાઇલ અપડેટ કરો", matchedSchemes: "મેળ ખાતી યોજનાઓ", savedSchemes: "સાચવેલી યોજનાઓ", applications: "અરજીઓ", recommended: "ભલામણ કરેલ", matchedToProfile: "તમારી પ્રોફાઇલ સાથે મેળ ખાતી યોજનાઓ", viewAll: "બધું જુઓ", recentActivity: "તાજેતરની પ્રવૃત્તિ", yourEvi: "તમારું EVI", registration: "ખેડૂત નોંધણી", newRegistration: "નવી ખેડૂત નોંધણી", previous: "પાછળ", continue: "ચાલુ રાખો", submitRegistration: "નોંધણી સબમિટ કરો" },
  kn: { farmerLoginTitle: "ರೈತರ ಲಾಗಿನ್", signInTitle: "ಕಿಸಾನ್ ಕನೆಕ್ಟ್‌ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ", mobileNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ", password: "ಪಾಸ್‌ವರ್ಡ್", login: "ಲಾಗಿನ್", farmerDashboard: "ರೈತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", welcome: "ಸ್ವಾಗತ", updateProfile: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ", matchedSchemes: "ಹೊಂದಾಣಿಕೆಯ ಯೋಜನೆಗಳು", savedSchemes: "ಉಳಿಸಿದ ಯೋಜನೆಗಳು", applications: "ಅರ್ಜಿಗಳು", recommended: "ಶಿಫಾರಸು", matchedToProfile: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದುವ ಯೋಜನೆಗಳು", viewAll: "ಎಲ್ಲವನ್ನೂ ನೋಡಿ", recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ", yourEvi: "ನಿಮ್ಮ EVI", registration: "ರೈತರ ನೋಂದಣಿ", newRegistration: "ಹೊಸ ರೈತರ ನೋಂದಣಿ", previous: "ಹಿಂದಿನ", continue: "ಮುಂದುವರಿಸಿ", submitRegistration: "ನೋಂದಣಿ ಸಲ್ಲಿಸಿ" },
  ks: { farmerLoginTitle: "کسان لاگ اِن", signInTitle: "کسان کنیکٹ منز سائن اِن کریو", mobileNumber: "موبایل نمبر", password: "پاس ورڈ", login: "لاگ اِن", farmerDashboard: "کسان ڈیش بورڈ", welcome: "خوش آمدید", updateProfile: "پروفایل اپڈیٹ کریو", matchedSchemes: "میل کھان والی سکیمہ", savedSchemes: "محفوظ سکیمہ", applications: "درخواست", recommended: "تجویز شدہ", matchedToProfile: "تُہند پروفایل کُن میل کھان والی سکیمہ", viewAll: "سٲری وُچھو", recentActivity: "حالیہ سرگرمی", yourEvi: "تُہند EVI", registration: "کسان رجسٹریشن", newRegistration: "نٔو کسان رجسٹریشن", previous: "پچھلا", continue: "جاری تھاویو", submitRegistration: "رجسٹریشن جمع کریو" },
  kok: { farmerLoginTitle: "शेतकार लॉगीन", signInTitle: "किसान कनेक्टांत सायन इन करात", mobileNumber: "मोबायल क्रमांक", password: "पासवर्ड", login: "लॉगीन", farmerDashboard: "शेतकार डॅशबोर्ड", welcome: "येवकार", updateProfile: "प्रोफायल अपडेट करात", matchedSchemes: "जुळपी येवजणो", savedSchemes: "जतन केल्ल्यो येवजणो", applications: "अर्ज", recommended: "शिफारस केल्ले", matchedToProfile: "तुमच्या प्रोफायलाक जुळपी येवजणो", viewAll: "सगळें पळयात", recentActivity: "निमाणी हालचाल", yourEvi: "तुमचो EVI", registration: "शेतकार नोंदणी", newRegistration: "नवी शेतकार नोंदणी", previous: "फाटीं", continue: "फुडें वचात", submitRegistration: "नोंदणी धाडात" },
  mai: { farmerLoginTitle: "किसान लॉगिन", signInTitle: "किसान कनेक्ट मे साइन इन करू", mobileNumber: "मोबाइल नंबर", password: "पासवर्ड", login: "लॉगिन", farmerDashboard: "किसान डैशबोर्ड", welcome: "स्वागत", updateProfile: "प्रोफाइल अपडेट करू", matchedSchemes: "मिलल योजना", savedSchemes: "सहेजल योजना", applications: "आवेदन", recommended: "सुझाओल", matchedToProfile: "अहाँक प्रोफाइल सँ मिलैत योजना", viewAll: "सभ देखू", recentActivity: "हालक गतिविधि", yourEvi: "अहाँक EVI", registration: "किसान पंजीकरण", newRegistration: "नव किसान पंजीकरण", previous: "पछिला", continue: "आगाँ बढ़ू", submitRegistration: "पंजीकरण जमा करू" },
  ml: { farmerLoginTitle: "കർഷക ലോഗിൻ", signInTitle: "കിസാൻ കണക്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക", mobileNumber: "മൊബൈൽ നമ്പർ", password: "പാസ്‌വേഡ്", login: "ലോഗിൻ", farmerDashboard: "കർഷക ഡാഷ്ബോർഡ്", welcome: "സ്വാഗതം", updateProfile: "പ്രൊഫൈൽ പുതുക്കുക", matchedSchemes: "പൊരുത്തപ്പെടുന്ന പദ്ധതികൾ", savedSchemes: "സേവ് ചെയ്ത പദ്ധതികൾ", applications: "അപേക്ഷകൾ", recommended: "ശുപാർശ ചെയ്തത്", matchedToProfile: "നിങ്ങളുടെ പ്രൊഫൈലുമായി പൊരുത്തപ്പെടുന്ന പദ്ധതികൾ", viewAll: "എല്ലാം കാണുക", recentActivity: "സമീപകാല പ്രവർത്തനം", yourEvi: "നിങ്ങളുടെ EVI", registration: "കർഷക രജിസ്ട്രേഷൻ", newRegistration: "പുതിയ കർഷക രജിസ്ട്രേഷൻ", previous: "മുമ്പത്തെ", continue: "തുടരുക", submitRegistration: "രജിസ്ട്രേഷൻ സമർപ്പിക്കുക" },
  mni: { farmerLoginTitle: "ꯈꯣꯡꯊꯥꯡ ꯂꯣꯒꯏꯟ", signInTitle: "ꯀꯤꯁꯥꯟ ꯀꯅꯦꯛꯇꯇꯥ ꯁꯥꯏꯟ ꯏꯟ ꯇꯧ", mobileNumber: "ꯃꯣꯕꯥꯏꯜ ꯅꯝꯕꯔ", password: "ꯄꯥꯁꯋꯔꯗ", login: "ꯂꯣꯒꯏꯟ", farmerDashboard: "ꯈꯣꯡꯊꯥꯡ ꯗꯦꯁꯕꯣꯔꯗ", welcome: "ꯇꯔꯥꯝꯅꯥ", updateProfile: "ꯄ꯭ꯔꯣꯐꯥꯏꯜ ꯑꯄꯗꯦꯠ", matchedSchemes: "ꯃꯦꯆ ꯑꯣꯏꯕ ꯁꯤꯀꯦꯝ", savedSchemes: "ꯊꯝꯖꯤꯟꯕ ꯁꯤꯀꯦꯝ", applications: "ꯑꯄꯂꯤꯀꯦꯁꯟ", recommended: "ꯁꯤꯐꯥꯔꯤꯁ", matchedToProfile: "ꯅꯍꯥꯛꯀꯤ ꯄ꯭ꯔꯣꯐꯥꯏꯜꯒꯥ ꯃꯦꯆ ꯑꯣꯏꯕ ꯁꯤꯀꯦꯝ", viewAll: "ꯄꯨꯝꯅꯃꯛ ꯎ", recentActivity: "ꯅꯨꯡꯉꯥꯏ ꯊꯧꯔꯥꯡ", yourEvi: "ꯅꯍꯥꯛꯀꯤ EVI", registration: "ꯈꯣꯡꯊꯥꯡ ꯂꯣꯏꯁꯤꯟ", newRegistration: "ꯑꯅꯧꯕ ꯈꯣꯡꯊꯥꯡ ꯂꯣꯏꯁꯤꯟ", previous: "ꯃꯃꯥꯡ", continue: "ꯆꯠꯊꯔꯁꯤ", submitRegistration: "ꯂꯣꯏꯁꯤꯟ ꯊꯥꯕ" },
  mr: { farmerLoginTitle: "शेतकरी लॉगिन", signInTitle: "किसान कनेक्टमध्ये साइन इन करा", mobileNumber: "मोबाइल क्रमांक", password: "पासवर्ड", login: "लॉगिन", farmerDashboard: "शेतकरी डॅशबोर्ड", welcome: "स्वागत आहे", updateProfile: "प्रोफाइल अपडेट करा", matchedSchemes: "जुळणाऱ्या योजना", savedSchemes: "जतन केलेल्या योजना", applications: "अर्ज", recommended: "शिफारस केलेले", matchedToProfile: "तुमच्या प्रोफाइलशी जुळणाऱ्या योजना", viewAll: "सर्व पहा", recentActivity: "अलीकडील गतिविधी", yourEvi: "तुमचा EVI", registration: "शेतकरी नोंदणी", newRegistration: "नवीन शेतकरी नोंदणी", previous: "मागील", continue: "पुढे जा", submitRegistration: "नोंदणी सादर करा" },
  ne: { farmerLoginTitle: "किसान लगइन", signInTitle: "किसान कनेक्टमा साइन इन गर्नुहोस्", mobileNumber: "मोबाइल नम्बर", password: "पासवर्ड", login: "लगइन", farmerDashboard: "किसान ड्यासबोर्ड", welcome: "स्वागत छ", updateProfile: "प्रोफाइल अपडेट गर्नुहोस्", matchedSchemes: "मिलेका योजनाहरू", savedSchemes: "सुरक्षित योजनाहरू", applications: "आवेदनहरू", recommended: "सिफारिस गरिएको", matchedToProfile: "तपाईंको प्रोफाइलसँग मिलेका योजनाहरू", viewAll: "सबै हेर्नुहोस्", recentActivity: "हालको गतिविधि", yourEvi: "तपाईंको EVI", registration: "किसान दर्ता", newRegistration: "नयाँ किसान दर्ता", previous: "अघिल्लो", continue: "जारी राख्नुहोस्", submitRegistration: "दर्ता पेश गर्नुहोस्" },
  or: { farmerLoginTitle: "ଚାଷୀ ଲଗଇନ୍", signInTitle: "କିଷାନ କନେକ୍ଟରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ", mobileNumber: "ମୋବାଇଲ୍ ନମ୍ବର", password: "ପାସୱାର୍ଡ", login: "ଲଗଇନ୍", farmerDashboard: "ଚାଷୀ ଡ୍ୟାସବୋର୍ଡ", welcome: "ସ୍ୱାଗତ", updateProfile: "ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ କରନ୍ତୁ", matchedSchemes: "ମେଳ ଖାଉଥିବା ଯୋଜନା", savedSchemes: "ସଞ୍ଚିତ ଯୋଜନା", applications: "ଆବେଦନ", recommended: "ସୁପାରିଶ", matchedToProfile: "ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ସହିତ ମେଳ ଖାଉଥିବା ଯୋଜନା", viewAll: "ସବୁ ଦେଖନ୍ତୁ", recentActivity: "ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ", yourEvi: "ଆପଣଙ୍କ EVI", registration: "ଚାଷୀ ପଞ୍ଜୀକରଣ", newRegistration: "ନୂଆ ଚାଷୀ ପଞ୍ଜୀକରଣ", previous: "ପୂର୍ବବର୍ତ୍ତୀ", continue: "ଆଗକୁ ବଢନ୍ତୁ", submitRegistration: "ପଞ୍ଜୀକରଣ ଦାଖଲ କରନ୍ତୁ" },
  pa: { farmerLoginTitle: "ਕਿਸਾਨ ਲਾਗਇਨ", signInTitle: "ਕਿਸਾਨ ਕਨੈਕਟ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ", mobileNumber: "ਮੋਬਾਈਲ ਨੰਬਰ", password: "ਪਾਸਵਰਡ", login: "ਲਾਗਇਨ", farmerDashboard: "ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ", welcome: "ਜੀ ਆਇਆਂ ਨੂੰ", updateProfile: "ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ", matchedSchemes: "ਮੇਲ ਖਾਂਦੀਆਂ ਯੋਜਨਾਵਾਂ", savedSchemes: "ਸੰਭਾਲੀਆਂ ਯੋਜਨਾਵਾਂ", applications: "ਅਰਜ਼ੀਆਂ", recommended: "ਸਿਫ਼ਾਰਸ਼ੀ", matchedToProfile: "ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਮੇਲ ਖਾਂਦੀਆਂ ਯੋਜਨਾਵਾਂ", viewAll: "ਸਭ ਵੇਖੋ", recentActivity: "ਹਾਲੀਆ ਸਰਗਰਮੀ", yourEvi: "ਤੁਹਾਡਾ EVI", registration: "ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ", newRegistration: "ਨਵੀਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ", previous: "ਪਿਛਲਾ", continue: "ਜਾਰੀ ਰੱਖੋ", submitRegistration: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਜਮ੍ਹਾਂ ਕਰੋ" },
  sa: { farmerLoginTitle: "कृषक प्रवेशः", signInTitle: "किसान कनेक्ट मध्ये प्रविशतु", mobileNumber: "चलभाष सङ्ख्या", password: "गुप्तशब्दः", login: "प्रवेशः", farmerDashboard: "कृषक पट्टिका", welcome: "स्वागतम्", updateProfile: "परिचय अद्यतनम्", matchedSchemes: "मेलिताः योजनाः", savedSchemes: "रक्षिताः योजनाः", applications: "आवेदनानि", recommended: "अनुशंसितम्", matchedToProfile: "भवतः परिचयेन मेलिताः योजनाः", viewAll: "सर्वं पश्यतु", recentActivity: "अद्यतन गतिविधिः", yourEvi: "भवतः EVI", registration: "कृषक पञ्जीकरणम्", newRegistration: "नूतन कृषक पञ्जीकरणम्", previous: "पूर्वम्", continue: "अग्रे गच्छतु", submitRegistration: "पञ्जीकरणं समर्पयतु" },
  sat: { farmerLoginTitle: "ᱠᱮᱥᱟᱱ ᱞᱚᱜᱤᱱ", signInTitle: "ᱠᱤᱥᱟᱱ ᱠᱚᱱᱮᱠᱴ ᱨᱮ ᱥᱟᱭᱤᱱ ᱤᱱ", mobileNumber: "ᱢᱳᱵᱟᱭᱤᱞ ᱱᱟᱢᱵᱟᱨ", password: "ᱯᱟᱥᱣᱟᱨᱰ", login: "ᱞᱚᱜᱤᱱ", farmerDashboard: "ᱠᱮᱥᱟᱱ ᱰᱮᱥᱵᱳᱨᱰ", welcome: "ᱡᱚᱦᱟᱨ", updateProfile: "ᱯᱨᱳᱯᱟᱭᱤᱞ ᱵᱟᱹᱲᱦᱟᱹᱣ", matchedSchemes: "ᱢᱮᱞ ᱡᱚᱡᱚᱜ ᱥᱠᱤᱢ", savedSchemes: "ᱡᱚᱢᱟ ᱥᱠᱤᱢ", applications: "ᱟᱵᱮᱫᱟᱱ", recommended: "ᱥᱤᱯᱷᱟᱨᱤᱥ", matchedToProfile: "ᱟᱢᱟᱜ ᱯᱨᱳᱯᱟᱭᱤᱞ ᱥᱟᱶ ᱢᱮᱞ ᱥᱠᱤᱢ", viewAll: "ᱡᱚᱛᱚ ᱧᱮᱞ", recentActivity: "ᱱᱟᱣᱟ ᱠᱟᱹᱢᱤ", yourEvi: "ᱟᱢᱟᱜ EVI", registration: "ᱠᱮᱥᱟᱱ ᱱᱚᱸᱫᱽᱦᱚᱱ", newRegistration: "ᱱᱟᱣᱟ ᱠᱮᱥᱟᱱ ᱱᱚᱸᱫᱽᱦᱚᱱ", previous: "ᱞᱟᱦᱟ", continue: "ᱞᱟᱦᱟ ᱥᱮᱱ", submitRegistration: "ᱱᱚᱸᱫᱽᱦᱚᱱ ᱡᱚᱢᱟ" },
  sd: { farmerLoginTitle: "هاري لاگ اِن", signInTitle: "ڪسان ڪنيڪٽ ۾ لاگ اِن ٿيو", mobileNumber: "موبائل نمبر", password: "پاسورڊ", login: "لاگ اِن", farmerDashboard: "هاري ڊيش بورڊ", welcome: "ڀليڪار", updateProfile: "پروفائل اپڊيٽ ڪريو", matchedSchemes: "ملندڙ اسڪيمون", savedSchemes: "محفوظ اسڪيمون", applications: "درخواستون", recommended: "سفارش ٿيل", matchedToProfile: "توهان جي پروفائل سان ملندڙ اسڪيمون", viewAll: "سڀ ڏسو", recentActivity: "تازو سرگرمي", yourEvi: "توهان جو EVI", registration: "هاري رجسٽريشن", newRegistration: "نئين هاري رجسٽريشن", previous: "پوئين", continue: "جاري رکو", submitRegistration: "رجسٽريشن جمع ڪريو" },
  ta: { farmerLoginTitle: "விவசாயி உள்நுழைவு", signInTitle: "கிசான் கனெக்டில் உள்நுழைக", mobileNumber: "மொபைல் எண்", password: "கடவுச்சொல்", login: "உள்நுழைவு", farmerDashboard: "விவசாயி டாஷ்போர்டு", welcome: "வரவேற்கிறோம்", updateProfile: "சுயவிவரத்தைப் புதுப்பிக்கவும்", matchedSchemes: "பொருந்திய திட்டங்கள்", savedSchemes: "சேமித்த திட்டங்கள்", applications: "விண்ணப்பங்கள்", recommended: "பரிந்துரைக்கப்பட்டது", matchedToProfile: "உங்கள் சுயவிவரத்துடன் பொருந்திய திட்டங்கள்", viewAll: "அனைத்தையும் பார்க்கவும்", recentActivity: "சமீபத்திய செயல்பாடு", yourEvi: "உங்கள் EVI", registration: "விவசாயி பதிவு", newRegistration: "புதிய விவசாயி பதிவு", previous: "முந்தையது", continue: "தொடரவும்", submitRegistration: "பதிவைச் சமர்ப்பிக்கவும்" },
  te: { farmerLoginTitle: "రైతు లాగిన్", signInTitle: "కిసాన్ కనెక్ట్‌లో సైన్ ఇన్ చేయండి", mobileNumber: "మొబైల్ నంబర్", password: "పాస్‌వర్డ్", login: "లాగిన్", farmerDashboard: "రైతు డ్యాష్‌బోర్డ్", welcome: "స్వాగతం", updateProfile: "ప్రొఫైల్ నవీకరించండి", matchedSchemes: "సరిపోలిన పథకాలు", savedSchemes: "దాచిన పథకాలు", applications: "దరఖాస్తులు", recommended: "సిఫార్సు", matchedToProfile: "మీ ప్రొఫైల్‌కు సరిపోలిన పథకాలు", viewAll: "అన్నీ చూడండి", recentActivity: "ఇటీవలి కార్యకలాపం", yourEvi: "మీ EVI", registration: "రైతు నమోదు", newRegistration: "కొత్త రైతు నమోదు", previous: "మునుపటి", continue: "కొనసాగించండి", submitRegistration: "నమోదు సమర్పించండి" },
  ur: { farmerLoginTitle: "کسان لاگ اِن", signInTitle: "کسان کنیکٹ میں سائن اِن کریں", mobileNumber: "موبائل نمبر", password: "پاس ورڈ", login: "لاگ اِن", farmerDashboard: "کسان ڈیش بورڈ", welcome: "خوش آمدید", updateProfile: "پروفائل اپ ڈیٹ کریں", matchedSchemes: "ملنے والی اسکیمیں", savedSchemes: "محفوظ اسکیمیں", applications: "درخواستیں", recommended: "تجویز کردہ", matchedToProfile: "آپ کی پروفائل سے ملنے والی اسکیمیں", viewAll: "سب دیکھیں", recentActivity: "حالیہ سرگرمی", yourEvi: "آپ کا EVI", registration: "کسان رجسٹریشن", newRegistration: "نئی کسان رجسٹریشن", previous: "پچھلا", continue: "جاری رکھیں", submitRegistration: "رجسٹریشن جمع کریں" }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("kisan_connect_language") || "en");
  const changeLanguage = (value) => { setLanguage(value); localStorage.setItem("kisan_connect_language", value); };
  const translate = (key) => translations[language]?.[key] || farmerCoreTranslations[language]?.[key] || translations.en[key] || key;
  return <LanguageContext.Provider value={{ language, changeLanguage, translate }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
